fix runtime error: 03-23 17:47:16.521: E/AndroidRuntime(6912): java.lang.RuntimeException: Unable to start activity ComponentInfo{net.learn2develop.swiping/net.learn2develop.swiping.MainActivity}: android.view.InflateException: Binary XML file line #6: Error inflating class android.support.v4.view.ViewPager
03-23 17:47:16.521: E/AndroidRuntime(6912): Caused by:
java.lang.ClassNotFoundException: android.support.v4.view.ViewPager in
loader
dalvik.system.PathClassLoader[/data/app/net.learn2develop.swiping-1.apk]